// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var $, app, marionette, _;
    $ = require('jquery');
    _ = require('underscore');
    marionette = require('marionette');
    require('bootstrap');
    app = new marionette.Application({
      root: "/fg"
    });
    app.addRegions({
      navigationRegion: "#navigation",
      mainRegion: "#mainContent",
      statusRegion: "#statusBar",
      modal: ModalRegion,
      dialogRegion: DialogRegion,
      fileBrowseRegion: FileBrowseRegion
    });
    app.on("start", function(opts) {
      console.log("App Started");
      return $("[rel=tooltip]").tooltip({
        placement: 'bottom'
      });
    });
    app.on("initialize:after", function() {
      return console.log("after init");
      /*fetch all settings
      */

    });
    app.addInitializer(function(options) {});
    /*return _.extend app,
      module: (additionalProps)->
        return _.extend
          Views: {}
          additionalProps
    */

    return app;
  });

}).call(this);
