// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var $, Backbone, marionette, _;
    $ = require('jquery');
    _ = require('underscore');
    Backbone = require('backbone');
    marionette = require('marionette');
    return new Backbone.Marionette.EventAggregator();
  });

}).call(this);
