// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var $, DataChannelView, boostrap, dummyTemplate, marionette, vent, _;
  $ = require('jquery');
  _ = require('underscore');
  boostrap = require('bootstrap');
  marionette = require('marionette');
  vent = require('../core/vent');
  dummyTemplate = require("text!./dataChannel.tmpl");
  DataChannelView = (function(_super) {

    __extends(DataChannelView, _super);

    DataChannelView.prototype.template = dummyTemplate;

    DataChannelView.prototype.ui = {
      contentEditor: "#messageEditor"
    };

    DataChannelView.prototype.events = {
      'change textarea ': 'updateContent'
    };

    function DataChannelView(options) {
      DataChannelView.__super__.constructor.call(this, options);
    }

    DataChannelView.prototype["delete"] = function() {
      return this.model.destroy();
    };

    DataChannelView.prototype.updateContent = function() {
      return console.log("blzh");
    };

    return DataChannelView;

  })(Backbone.Marionette.ItemView);
  return DataChannelView;
});
