// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var $, DropBoxStorage, Dummy, boostrap, marionette, _;
    $ = require('jquery');
    _ = require('underscore');
    boostrap = require('bootstrap');
    marionette = require('marionette');
    DropBoxStorage = require('./storage/dropboxStorage');
    Dummy = (function(_super) {

      __extends(Dummy, _super);

      "PathRoot is used similarly to Backbones urlRoot";


      Dummy.prototype.defaults = {
        name: "mainPart",
        ext: "coscad",
        content: ""
      };

      Dummy.prototype.idAttribute = 'name';

      Dummy.prototype.sync = DropBoxStorage.sync;

      Dummy.prototype.pathRoot = "";

      function Dummy(attributes, options) {
        Dummy.__super__.constructor.call(this, attributes, options);
        console.log(attributes);
        this.pathRoot = options.pathRoot;
      }

      return Dummy;

    })(Backbone.Model);
    return Dummy;
  });

}).call(this);
