// Generated by CoffeeScript 1.3.3

define(function(require) {
  var $, Backbone, WebRTCApp, app, marionette, _;
  $ = require('jquery');
  _ = require('underscore');
  Backbone = require('backbone');
  marionette = require('marionette');
  WebRTCApp = require('modules/webrtc.app');
  app = new WebRTCApp();
  /*return _.extend app,
    module: (additionalProps)->
      return _.extend
        Views: {}
        additionalProps
  */

  return app;
});
